// Hero card at the top of every report — the plain-English narrative the
// product name promises. Hidden entirely when the backend Groq integration is
// disabled or the call failed (aiSummary will be empty).
import { CardShell } from "../ui/CardShell";

export function AISummaryCard({ summary }: { summary?: string }) {
  if (!summary || !summary.trim()) return null;

  const paragraphs = summary
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <CardShell variant="primary">
      <div className="px-5 pt-5 pb-4 flex items-center gap-2 border-b border-zinc-800/80">
        <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-violet-300 uppercase tracking-wider leading-none">
          <SparkIcon />
          In plain English
        </span>
        <span className="text-[10px] font-bold rounded px-1.5 py-px leading-none text-violet-300 bg-violet-950 border border-violet-800">
          AI summary
        </span>
      </div>

      <div className="p-5 flex flex-col gap-3 leading-relaxed text-zinc-200">
        {paragraphs.map((p, i) => (
          <p
            key={i}
            className={i === 0 ? "text-zinc-100 text-[15px] leading-relaxed" : "text-sm text-zinc-300"}
          >
            {p}
          </p>
        ))}
      </div>

      <div className="px-5 pb-4 -mt-1 text-[10px] text-zinc-600 flex items-center gap-1.5">
        <span className="w-1 h-1 rounded-full bg-violet-500/60" />
        Generated by Llama 3.3 (via Groq) from this run's signals. May contain mistakes.
      </div>
    </CardShell>
  );
}

function SparkIcon() {
  return (
    <svg
      width="11"
      height="11"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M12 3l1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3z" />
    </svg>
  );
}
