import { describe, expect, it } from "vitest";
import { formatReport } from "../src/utils/reportFormatter";
import type { AnalysisResult } from "../src/types/analysis";

const sampleResult: AnalysisResult = {
  url: "https://example.com",
  fetchedAt: "2026-04-13T12:00:00Z",
  overview: {
    title: "Example",
    description: "Example site",
    favicon: "",
    language: "en",
    pageLoadHint: "lightweight",
  },
  techStack: [{ name: "React", category: "framework", confidence: "high" }],
  seoChecks: [{ id: "https", label: "HTTPS", status: "pass", detail: "ok" }],
  ux: {
    hasCTA: true,
    ctaCount: 1,
    hasForms: true,
    formCount: 1,
    hasSocialProof: false,
    hasTrustSignals: true,
    hasContactInfo: true,
    mobileReady: true,
    hasCookieBanner: false,
    hasLiveChat: false,
    hasVideoContent: false,
    hasNewsletterSignup: false,
    hasPrivacyPolicy: true,
  },
  pageStats: {
    wordCount: 100,
    imageCount: 2,
    internalLinks: 3,
    externalLinks: 1,
    scriptCount: 2,
    h1Count: 1,
    h2Count: 2,
    h3Count: 1,
    stylesheetCount: 1,
    inlineStyleCount: 0,
    lazyImageCount: 1,
    fontCount: 1,
    renderBlockingScripts: 0,
    contentToCodeRatio: 30,
    videoCount: 0,
  },
  contentStats: {
    topKeywords: ["example"],
    avgSentenceLen: 10,
    readingLevel: "simple",
  },
  weakPoints: ["Missing social proof"],
  recommendations: ["Add testimonials"],
  intent: {
    category: "general",
    label: "General Website",
    description: "General purpose content.",
  },
  customerView: {
    offerClear: true,
    ctaClear: true,
    trustLevel: "moderate",
    statements: ["Clear offer."],
  },
  conversionScores: {
    overall: 80,
    clarity: 90,
    trust: 70,
    ctaStrength: 80,
    friction: 80,
    clarityNote: "good",
    trustNote: "good",
    ctaNote: "good",
    frictionNote: "good",
  },
  firstImpression: {
    score: 8,
    label: "Good",
    explanation: "Looks good.",
  },
  biggestOpportunity: "Improve social proof",
  competitorInsight: "Differentiate messaging",
  prioritizedIssues: [{ rank: 1, issue: "Social proof", impact: "Trust", why: "Needed" }],
  eli5: [{ technical: "No social proof", simple: "Add testimonials." }],
  aiDetection: {
    isAIBuilt: false,
    confidence: "medium",
    builder: "",
    signals: [],
  },
};

describe("formatReport", () => {
  it("includes key sections", () => {
    const text = formatReport(sampleResult);
    expect(text).toContain("WEBSITE ANALYSIS REPORT");
    expect(text).toContain("SEO AUDIT");
    expect(text).toContain("RECOMMENDATIONS");
    expect(text).toContain("Generated by Explain This Website");
  });
});
